### ISSUE TITLE
normalised count table (deseq2)?

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#102]
Hi team 
Thanks so much for the DESeq2 workflow in SARTools.
Could you please let me know if there is anyway to download normalised counts in the deseq2 workflow?
Thanks in advance 
M

**Comment by hvaret** [comment]
Hi,
the normalized counts are exported by SARTools into the *complete.txt files, see the columns starting with "norm".
Best,
Hugo
