### ISSUE TITLE
pvalue rather than adjusted pvalue in deseq2 workflow?

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#103]
Hi .. is it possible to use pvalue rather than adjusted p-value in the deseq2? how?

Generally speaking, what do you think is the most commonly used method in deseq2 from what you heard of (e.g. parametric, local)?

Thanks :)

**Comment by hvaret** [comment]
Hi,
you have to use the adjusted p-values that are made to handle the multiple testing problem.
Then, the "parametric" method should work well on most datasets, but I can't tell you more about this parameter.
Best,
Hugo

**Comment by marwa38** [comment]
Thanks for your response @hvaret 
Does your workflow use the argument `alpha` for both pvalue and adjusted pvalue?
The problem is that some studies do adjusted pvalue of 0.1 but as far as I can see that alpha in your workflow also means the pvalue? So could it be possible to have an argument for each?

**Comment by hvaret** [comment]
The `alpha` parameter in SARTools is applied to the adjusted p-value to export the lists of differentially expressed genes in separate files (up and down). Note that It is also used during the independent filtering procedure but it should have a low effect here.

**Comment by marwa38** [comment]
Many Thanks @hvaret for clarifiying alpha argument within your workflow. As the results I got from SARTools are more trustworthy and biologically significant (at pathway level) than other methods I used, I exported the deseq2 object outside SARtools to make the filtering at pvalue <0.01 (not adjusted pvalue) and log2foldchange of 0.1 (>0.1 for up and <-0.1 for down). Can I do that in SARTools?

**Comment by hvaret** [comment]
No you can't do that with SARTools as it applies a cutoff only on the adjusted p-values (not on the log2FC).
Note that you must be careful when filtering on the p-values as you no longer control the false discovery rate.

**Comment by marwa38** [comment]
@hvaret

Could you please confirm that the results table in the output vector `out.DESeq2` after running `run.DESeq2`  is at FDR < 0.05? 
Why I am asking? as the output table have other FDRs > 0.05 (attached table below after the code if need to have a look).
```
rm(list=ls())                                        # remove all the objects from the R session

workDir <- "/home/r01mt19/Documents/NP_papers/transcriptome/NP_devStages"      # working directory for the R session

projectName <- "NP_devStages_RNAseq_stim"                         # name of the project
author <- "Marwa Tawfik"                                # author of the statistical analysis/report

targetFile <- "/home/r01mt19/Documents/NP_papers/transcriptome/NP_devStages/devStages/featureCounts/SARTools/target_stim.txt"                           # path to the design/target file
rawDir <- "/home/r01mt19/Documents/NP_papers/transcriptome/NP_devStages/devStages/featureCounts/SARTools/raw/stimulus"                                      # path to the directory containing raw counts files
#featuresToRemove <- c("alignment_not_unique",        # names of the features to be removed
#                      "ambiguous", "no_feature",     # (specific HTSeq-count information and rRNA for example)
#                      "not_aligned", "too_low_aQual")# NULL if no feature to remove
featuresToRemove <- NULL # NULL if no feature to remove
varInt <- "diet"                                    # factor of interest
condRef <- "M"                                      # reference biological condition
batch <- NULL                                        # blocking factor: NULL (default) or "batch" for example

fitType <- "parametric"                              # mean-variance relationship: "parametric" (default), "local" or "mean"
cooksCutoff <- TRUE                                  # TRUE/FALSE to perform the outliers detection (default is TRUE)
independentFiltering <- TRUE                         # TRUE/FALSE to perform independent filtering (default is TRUE)
alpha <- 0.05                                                  # threshold of statistical significance
pAdjustMethod <- "BH"                                # p-value adjustment method: "BH" (default) or "BY"

typeTrans <- "VST"                                   # transformation for PCA/clustering: "VST" or "rlog"
locfunc <- "median"                                  # "median" (default) or "shorth" to estimate the size factors

colors <- c("#f3c300", "#875692", "#f38400",         # vector of colors of each biological condition on the plots
            "#a1caf1", "#be0032", "#c2b280",
            "#848482", "#008856", "#e68fac",
            "#0067a5", "#f99379", "#604e97")

forceCairoGraph <- FALSE

library(SARTools)
if (forceCairoGraph) options(bitmapType="cairo")

# checking parameters
checkParameters.DESeq2(projectName=projectName,author=author,targetFile=targetFile,
                       rawDir=rawDir,featuresToRemove=featuresToRemove,varInt=varInt,
                       condRef=condRef,batch=batch,fitType=fitType,cooksCutoff=cooksCutoff,
                       independentFiltering=independentFiltering,alpha=alpha,pAdjustMethod=pAdjustMethod,
                       typeTrans=typeTrans,locfunc=locfunc,colors=colors)

# loading target file
target <- loadTargetFile(targetFile=targetFile, varInt=varInt, condRef=condRef, batch=batch)

# loading counts
counts <- loadCountData(target=target, rawDir=rawDir, featuresToRemove=featuresToRemove)

# description plots
majSequences <- descriptionPlots(counts=counts, group=target[,varInt], col=colors)

out.DESeq2 <- run.DESeq2(counts=counts, target=target, varInt=varInt, batch=batch,
                         locfunc=locfunc, fitType=fitType, pAdjustMethod=pAdjustMethod,
                         cooksCutoff=cooksCutoff, independentFiltering=independentFiltering, alpha=alpha)

write.table(out.DESeq2$results$V_vs_M, "tables/out.DESeq2$results$V_vs_M.tsv", sep="\t", quote=F, col.names=NA)
```
[out.DESeq2$results$V_vs_M.tsv.txt](https://github.com/PF2-pasteur-fr/SARTools/files/12498748/out.DESeq2.results.V_vs_M.tsv.txt)

**Comment by hvaret** [comment]
The `out.DESeq2` object contains all the results (i.e. for all the genes) and they are only split into up and down files in the `tables` directory using the `alpha` threshold on the adjusted p-values.
