### ISSUE TITLE
Fold change calculation?

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#104]
Hi 

Please check how Fold Change (in the complete.txt file) was calculated as I assume that it was wrongly calculated. 
What is the equation you used to calculate fold change from log2foldchange?

Does this how you calculated it? (I used in excel to clarify)
`=IF(AI2>=0, 2^AI2, 2^ABS(AI2))`
Or I am missing something?

Thank you in advance

**Comment by marwa38** [comment]
Here is an example that is different in the calculated one with the equation I mentioned above and the SARTools calculations
The same results as yours in the positive log 2-fold change (l2fc), but in the negative l2fc, my calculations (T) are different from yours (Column S); as attached
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/3290d505-de06-4ea1-b57b-db892eff1f98)

Please let me know @scottdaniel  @rlegendre @hvaret @Sismeiro as I need to submit my manuscript including the fold change column. 
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/f3c0e0d9-b090-412b-888b-76743c1f3682)

**Comment by hvaret** [comment]
You're mistaken, the formula for the FoldChange is actually 2^log2(FoldChange) to have Fold-Changes either higher than 1 or lower than 1. In your case you only have Fold-Changes higher than 1 and one can't know if the gene is up or down-regulated.
