### ISSUE TITLE
[WARNING] Could not fetch resource figures

### ISSUE THREAD

**Issue by scauchi59** [PF2-pasteur-fr/SARTools#105]
Hi, I recently analyzed RNA-seq data using SARTools on Galaxy. The analysis report is complete, but I can't retrieve the comparison results that should be in .txt format. When I click the link, I get an HTML file without the expected data instead of a text file with the results. So I turned to the R package. The analysis is similar to what I obtained with Galaxy. I was also able to retrieve the comparison results (out.DESeq2$results), but this time I can no longer visualize the figures. I saw this message when I requested the final report:

[WARNING] Could not fetch resource figures/barplotTotal.png
[WARNING] Could not fetch resource figures/barplotNull.png
[WARNING] Could not fetch resource figures/densplot.png
[WARNING] Could not fetch resource figures/majSeq.png
[WARNING] Could not fetch resource figures/pairwiseScatter.png
[WARNING] Could not fetch resource figures/cluster.png
[WARNING] Could not fetch resource figures/PCA.png
[WARNING] Could not fetch resource figures/diagSizeFactorsHist.png
[WARNING] Could not fetch resource figures/diagSizeFactorsTC.png
[WARNING] Could not fetch resource figures/countsBoxplots.png
[WARNING] Could not fetch resource figures/dispersionsPlot.png
[WARNING] Could not fetch resource figures/rawpHist.png
[WARNING] Could not fetch resource figures/MAPlot.png
[WARNING] Could not fetch resource figures/volcanoPlot.png

Can you please help me solve the problem on galaxy and the problem on R?

Thanks in advance for your help,

Best Regards,

Stephane

**Comment by hvaret** [comment]
Hi,
thanks for your message, I just try with a toy data set and everything seems OK.
Are the plots (png files) correctly exported in the `figures` directory? What are your versions of R and SARTools?
Best,
Hugo

**Comment by scauchi59** [comment]
Bonjour, merci pour votre réponse rapide. Ce sera peut-être plus simple en français. J'utilise la version R 4.3.1. Pour le script, j'utilise celui sur Github de "March 23rd, 2022 designed to be executed with SARTools 1.8.1". Et pour les figures, elles ne sont en effet pas exportées vers la "figures directory". En tout cas je ne les vois pas dans le "workdir" défini dans le script. Faut-il définir en plus un dossier pour exporter les figures ?


Merci pour votre aide et bonne journée,


Stéphane

________________________________
De : Hugo Varet ***@***.***>
Envoyé : lundi 23 octobre 2023 09:46:04
À : PF2-pasteur-fr/SARTools
Cc : CAUCHI Stephane; Author
Objet : Re: [PF2-pasteur-fr/SARTools] [WARNING] Could not fetch resource figures (Issue #105)


Hi,
thanks for your message, I just try with a toy data set and everything seems OK.
Are the plots (png files) correctly exported in the figures directory? What are your versions of R and SARTools?
Best,
Hugo

**Comment by hvaret** [comment]
Bonjour,
comme ça je ne vois pas d'où peut venir le problème. Pouvez-vous m'envoyer le script et les données pour que je reproduise l'erreur ?
Cordialement,
Hugo VAret

**Comment by scauchi59** [comment]
Merci pour votre aide,


J'étais sur le point de vous envoyer mes données et le script quand je me suis aperçu en le refaisant tourner qu'il y avait une erreur dans mon script (un "/" manquant") qui empêchait d'adresser les figures au bon endroit. Je suis sous MacOs. J'ai réussi à faire tourner SARTools sans problème, j'ai le rapport et les figures attendues. Désolé pour le dérangement, et merci encore pour votre aide. Je vais contacter la team qui s'occupe de Galaxy parce-que je sais que d'autres personnes qui ne maitrisent pas beaucoup R sont dans le même cas que moi.


Merci encore pour cet excellent outil d'analyse,


Stéphane CAUCHI

________________________________
De : Hugo Varet ***@***.***>
Envoyé : lundi 23 octobre 2023 14:13:50
À : PF2-pasteur-fr/SARTools
Cc : CAUCHI Stephane; Author
Objet : Re: [PF2-pasteur-fr/SARTools] [WARNING] Could not fetch resource figures (Issue #105)


Bonjour,
comme ça je ne vois pas d'où peut venir le problème. Pouvez-vous m'envoyer le script et les données pour que je reproduise l'erreur ?
Cordialement,
Hugo VAret
