### ISSUE TITLE
prefiltering of low gene counts in deseq2 pipeline?

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#106]
Hi team 

For deseq2 it is advisable by their workflow to do some prefiltering to remove genes that have low counts. Could you pleae let me know if this part of the SARTools deseq2 pipeline or I need to do that before using SARTools?

Thanks in advance 
Marwa

**Comment by marwa38** [comment]
For more clarify how to use this part of the template code to filter out those with counts lower than 10. 
```
#featuresToRemove <- c("alignment_not_unique",        # names of the features to be removed
#                      "ambiguous", "no_feature",     # (specific HTSeq-count information and rRNA for example)
#                      "not_aligned", "too_low_aQual")# NULL if no feature to remove 
```

**Comment by hvaret** [comment]
By default DESeq2 uses an "independent filtering" algorithm before adjusting the p-values. You can use either this method OR filter the low counts before the analysis, but I think it's not a good strategy to perform both.
