### ISSUE TITLE
two columns between baseMean and FoldChange in complete.txt file? 

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#107]
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/0972c847-70b4-47d8-9f93-7fa368757f6c)
Could you please let me know what is between baseMean and fold change?
These are the names of the two groups I compared but not clear in the complete.txt table what those 2 columns denotes to?
Thanks for clarifying in advance 
Marwa

**Comment by hvaret** [comment]
As explained in the HTML report, these columns are the means (rounded) of normalized counts of the biological conditions.
