### ISSUE TITLE
normalisation on all groups or pairwise?

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#108]
Hi team 

isn't it advisable to run the normalisation on all of the group gene counts ? and not pairwise? asking as I am running deseq2 in SARTools on each two comparisons (pairwise) AvsB BvsC, AvsC and I have 28 comparisons. 

Thanks
Marwa

**Comment by hvaret** [comment]
Hi,
the normalisation is actually performed on all the samples simultaneously, not using the samples involved in a comparison.
Best,
Hugo

**Comment by marwa38** [comment]
Thanks for this @hvaret . But to have a biological reference group, we add the params for two groups only as if we run the template code on all groups, the reference group can’t be set for all pairwise comparison to be only one group. Please let me know. Thank you again.

**Comment by hvaret** [comment]
I'm sorry, I do not understand your question. Could you please give me an example?

**Comment by marwa38** [comment]
Thanks again 
So I use the SARTools template code that I run for each two group to do the pairwise comparison so I can the reference group (condRef), for example A vs B where B is the reference group. But in case I made all the comparisons in one template I can’t choose more than one reference because we have 28 comparisons. Hope that make sense ? This means we do the normalisation for each 2 group? When we run the template on each comparison separately.

**Comment by hvaret** [comment]
The normalisation is always performed on the samples simultaneously. The pairwise comparisons are then tested in a second step. One global reference condition (specified in the parameters, let's say "A") is set and taken into account for the first comparisons involving A, but then the reference condition for the next comparisons depends on the samples are ordered in the design file.
