### ISSUE TITLE
ERROR: dependency ‘SummarizedExperiment’ is not available for package ‘SARTools’

### ISSUE THREAD

**Issue by ChristopheH** [PF2-pasteur-fr/SARTools#12]
Hello,

I tried to follow this page to install SARTools : https://github.com/PF2-pasteur-fr/SARTools
Unfortunately when I use the command 
`install_github("PF2-pasteur-fr/SARTools", build_vignettes=TRUE)`
I have this error : 
```
> install_github("PF2-pasteur-fr/SARTools", build_vignettes=TRUE)
Downloading GitHub repo PF2-pasteur-fr/SARTools@master
from URL https://api.github.com/repos/PF2-pasteur-fr/SARTools/zipball/master
Installing SARTools
Skipping 6 unavailable packages: DESeq2, edgeR, genefilter, limma, S4Vectors, SummarizedExperiment
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD build  \
  '/tmp/RtmpJ7wBu4/devtools88df2ee25c/PF2-pasteur-fr-SARTools-94bd77b'  \
  --no-resave-data --no-manual 

* checking for file ‘/tmp/RtmpJ7wBu4/devtools88df2ee25c/PF2-pasteur-fr-SARTools-94bd77b/DESCRIPTION’ ... OK
* preparing ‘SARTools’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
      -----------------------------------
ERROR: dependency ‘SummarizedExperiment’ is not available for package ‘SARTools’
* removing ‘/tmp/RtmpQsrp0H/Rinst93a8774d3f7b/SARTools’
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
```
It looks like it does not find the previously installed DESeq2, edgeR and genefilter package, but also other packages such as SummarizedExperiment. So it makes the installation fail.

Could you please help me to install Sartools ? I am trying to install it under debian 8.

Thank you.

**Comment by hvaret** [comment]
Dear Christophe,
which version of R are you using? Could you check that DESeq2 is actually installed running `library(DESeq2)`?
DESeq2 requires the SummarizedExperiment package to be installed, I think there has been a problem during this step.
Thanks,
Hugo

**Comment by ChristopheH** [comment]
Hi Hugo,

Sorry, it looks like it was an issue related to bioconductor. I solved it with uninstall/install bioclite.

Do you have any example data/commands to test if the installation went well ?

Thank you for your help.

**Comment by hvaret** [comment]
To test the installation you can simply run `library(SARTools)`. You can then try the pipeline using the few command lines provided within the vignette (see section 5).

Best,

Hugo

**Comment by ChristopheH** [comment]
Thank you for this suggestion. I have another error that might be the "real one" : 
```
Error in title(...) : 
  X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 5 at size 15 could not be loaded
Calls: descriptionPlots ... plot.density -> plot.default -> localTitle -> title
Execution halted
```
I'm working on a way to fix this.

**Comment by ChristopheH** [comment]
It was indeed a problem with cairo. I had to uninstall/install R from sources with : 
./configure --with-x=yes --with-cairo=yes --with-libpng=yes
