### ISSUE TITLE
Segment fault

### ISSUE THREAD

**Issue by yifangt** [PF2-pasteur-fr/SARTools#15]
Hello,
I moved this post from comment to "issue" to seek for some help as I met problem when I ran SARTools.
```
*** caught segfault ***
address 0x68, cause 'memory not mapped'

Traceback:
 1: dev.off()
 2: pairwiseScatterPlots(counts = counts, group = group)
 3: descriptionPlots(counts = counts, group = target[, varInt], col = colors)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault
```
I can see the part of the results (figures subfolder), which are:
barplotNull.png barplotTotal.png densplot.png majSeq.png pairwiseScatter.png

And here is my R environment:
```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux stretch/sid
locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base 
> packageVersion("DESeq2")
[1] ‘1.12.3’
> packageVersion("SARTools")
[1] ‘1.3.1’
```
And some of my computer info are:
```
$ uname -a
Linux Cherry 4.3.0-1-amd64 #1 SMP Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux
$ free -h
              total        used        free      shared  buff/cache   available
Mem:           1.5T         10G        360G        250G        1.1T        1.2T
Swap:          499M        496M        3.5M
```
I just realized my experiment design is different from the demo target.txt, which contains three groups for comparisons of every two:
```
label       files   Treatment   group
sample01 file01    E    X
sample02 file02    E    X
......
sample13 file13    M    Y
sample14 file14    M    Y
......
sample25 file25    L    Z
sample26 file26    L    Z
```
Do you have any clue what possibly caused the segfault problem? Thanks a lot!

P.S. At first It seems to me the problem is related to the pairwiseScatterPlots()  function for 3-group of samples. However, when I use the same sets of data but only use 2-group "fake" treatment for testing purpose, same problem. 
I have 42 samples in total, each with ~177Million geneID. I did not see any RAM issues from my RAM consumption track (one test was carried out with 1.5TB RAM).

Also I tried fresh installation with two different computers, same problem. As Hugo mentioned the update all the packages of the computer, and I assumed the pkgs are "R pkgs" and some related ones like libcurl4, xml2, openssl etc, which are updated.

Hope to get some more ideas. Thanks again!

Yifang

**Comment by hvaret** [comment]
Hi Yifang,

thanks for having moved your message into the issue section.

I am not used to run SARTools on a so high number of features, it may be the reason of the bug. Could you try to run SARTools on a small number of genes (say about 50000)? The other reason could be the number of samples, could you try to run SARTools with all your genes but with a small number of samples (6 for example)?

Thanks for your bug report, hope it will work!

Best,

Hugo

**Comment by hvaret** [comment]
Dear Yifang and Heath,

I just updated SARTools (version 1.3.2 now) to avoid generating the pairwise scatter-plot when there are more than 30 samples in the counts matrix. The problem was that the width and height of the .png file were too high. I hope all will be OK now!

Best,

Hugo

**Comment by hobrien** [comment]
works great now. thanks!

**Comment by hobrien** [comment]
Hi Hugo,

This problem still happens for me when analysing a dataset with 29 samples. You may want to consider lowering this threshold slightly
