### ISSUE TITLE
Issue with pairwiseScatterPlots

### ISSUE THREAD

**Issue by royfrancis** [PF2-pasteur-fr/SARTools#17]
```
majSequences <- descriptionPlots(counts=counts, group=target[,varInt], col=colors)
Error in png(filename = "figures/pairwiseScatter.png", width = 800 * ncol,  : 
  unable to start png() device
In addition: Warning messages:
1: In png(filename = "figures/pairwiseScatter.png", width = 800 * ncol,  :
  unable to allocate bitmap
2: In png(filename = "figures/pairwiseScatter.png", width = 800 * ncol,  :
  opening device failed
```

The figure is not plotted but everything else works. `png()` works normally for me. When sourcing the whole template file, the code breaks at this point due to this error. But if I manually run blocks of code, the whole analysis reaches completion.

**Comment by hvaret** [comment]
Thanks for the bug report. How many samples are you studying? I fixed a bug in this function today, could you update SARTools and test if you still have this error?

Thanks,

Hugo

**Comment by royfrancis** [comment]
Yes. I do not get this error in the new version.
