### ISSUE TITLE
SamSeq, Limma and NoiSeq

### ISSUE THREAD

**Issue by royfrancis** [PF2-pasteur-fr/SARTools#19]
This is quite a handy package. Do you plan to add other packages such as SamSeq,  Limma and NoiSeq?

**Comment by hvaret** [comment]
Hello,
DESeq2 and edgeR are R packages we use everyday so we prefer to stay focused on them, but I will let you know if we plan to include limma. For SamSeq and NoiSeq we do not plan to include them.
Best,
Hugo
