### ISSUE TITLE
error in statistics tables

### ISSUE THREAD

**Issue by AlexandraBomane** [PF2-pasteur-fr/SARTools#20]
Hello !

I have a problem with my statistics tables obtained after running SARTools with DESeq2 package.
The calculations made in FoldChange and log2FoldChange fields seem incorrect.

Here an entry for example : 

Id : YAL002W
s1-condA : 17  
s2-condA : 23  
s3-condB : 35  
s4-condB : 45  
norm.s1-condA : 26  
norm.s2-condA : 28  
norm.s3-condB : 28  
norm.s4-condB : 29  
baseMean : 27.91  
**condA : 27  
condB : 28  
FoldChange : 1.01  
log2FoldChange : 0.015**  
pvalue : 0.885040513937845  
padj : 0.999879379281527  
dispGeneEst : 0 
dispFit : 0.099 
dispMAP : 0.083 
dispersion : 0.083  
betaConv : TRUE 
maxCooks : NA

My condition of reference is condA.

If I'm correct, FoldChange = 28/27= 1,037037037 --> around to 1.04. Here we have 1.01 instead.
And log2FoldChange = log2(1,037037037) = 0,052467 --> around to 0.052. Here we have 0.015 instead.

I want to know if there's an explanation for this inconsistency. Because if there's an error, so pvalue and padj could be questioned too...

Thanks,
Alexandra

**Comment by hvaret** [comment]
Dear Alexandra,
all is correct, the difference between the ratio B/A and the Fold-Change comes from the shrinkage of the log2(FC) in DESeq2. I think you could find more details about this procedure in the DESeq2 vignette.
Best regards,
Hugo

**Comment by AlexandraBomane** [comment]
Thank you very much Hugo,
I was sure that it couldn't be a gross mistake but I didn't understand.
I'll check the doc of DESeq2.
And thanks for SARTools, it's a great tool ;)

Best regards,
Alexandra

**Comment by AlexandraBomane** [comment]
Is it possible to disable the shrinkage in SARTools ?

Thanks,
Alexandra

**Comment by hvaret** [comment]
Unfortunately it is not possible at the moment, you have to use DESeq2 directly. However I will think about adding this option in a future version!
Hugo
