### ISSUE TITLE
Sartools normalization vs DESeq2 normalization with multiple groups

### ISSUE THREAD

**Issue by mthernando** [PF2-pasteur-fr/SARTools#22]
Hi Hugo, I have performed the comparison for six groups (at the same time) both with Sartools and DESeq2 manually. When I obtain the normalized counts (the table) I observe counts are different in both programs. However, if I took only two groups (G1 vs G2) and I perform with both programs (Sartools and DESeq2) normalized counts are exactly the same. My question is: is Sartools normalizing raw counts with additional factors than DESeq does when are several groups? I would appreciate your help. 

maría

**Comment by hvaret** [comment]
Hi Maria,
SARTools uses the DESeq2 normalization without any supplementary adjustment (when exporting the results, there is just a round() step). Could you send me your data to be able to reproduce your observations?
Best,
Hugo

**Comment by mthernando** [comment]
Thanks!
