### ISSUE TITLE
Factor variables

### ISSUE THREAD

**Issue by baj12** [PF2-pasteur-fr/SARTools#24]
In R it is possible to define a factor with numerical levels:

levels (df$col1) = c(1:4)

After saving such a file as a text file and reading it using SARTools it is not converted into a factor and thus cannot be used as a batch effect for example....

**Comment by hvaret** [comment]
Hi Bernd,
from a statistical point of view, it is possible to use a numeric variable as a blocking factor (e.g. age or BMI). I would advice you to redefine your variable using at least one character: r1, r2, r3 and so on for instance. R will then import the target file and consider this variable as a factor.
Hugo

**Comment by fabiansan** [comment]
Hi, maybe my question belongs to here as it also has something to do with the design formula input / blocking / statistics.
I have the following setup:
- 6 different cell lines (including 1 control cell line for all) -> the group variable representing the cell lines
- 6 time points
- 3 biological replicates for 3 cell lines over all time points and 4 biological for the other ones.

My varInt is group with the control cell line as condRef for sarTools and I am running the template_DESeq2 script.

As the raw data was genereted in differnent batches (different months) I wanted to use them for blocking/batch input, independet of the time series. Here I defined "batch1", "batch2" and "batch3" in the Batch column.
If I run template_script_DESeq2.r with batch = my Batch column, then DESeq2 fails to runs and returns the following error:
Error in checkFullRank(modelMatrix) : 
  the model matrix is not full rank, so the model cannot be fit as specified.
  One or more variables or interaction terms in the design formula are linear
  combinations of the others and must be removed.

Defining batch <- NULL everything runs smoothly.

I read 
https://support.bioconductor.org/p/64480/
https://support.bioconductor.org/p/62357/
https://support.bioconductor.org/p/63134/#63146
but don't know how could implement this in the template so far. 
Do you have any suggestions?

Example of my target.txt:
label	 files	group	BioRep	Day	Batch
ctrl	...	 ctrlCellLine	1	3	batch1
...
cond1	...	CellLine1	1	3	batch2
...
cond2	...	CellLine2	1	3	batch3

**Comment by hvaret** [comment]
Dear @fabiansan,
the problem here is that the "batch" variable seems to be confounded with the "group" variable (one is at least a linear combination of the other). From a statistical point of view, it is impossible to fit a model as we won't be able to attribute the observed variability to the "batch" or to the "group" variable. Moreover, with such a design it will be difficult to know if the differences between the cell lines actually come from the cell lines or from the batch effect as there is a confounding effect.
Best regards,
Hugo

**Comment by fabiansan** [comment]
Hi Hugo,

thanks for the repsonse and I see the reason. But I kind of shortend the table in a wrong way.
Only one sample file (out of 108) is marked as batch2 as the company had some problems with one sample and they measured it on another flow cell but this sample belonged to the same experimental setup as in batch1. I only wanted to account for the different technical procedure. Batch3 is another experiment few months later. So in total I have 108 sample files. 53 for batch1, 1 for batch2 and 54 for batch3. Right now I gues, that 1 file for batch2 is too less for fitting a model either. Am I right?

**Comment by hvaret** [comment]
Yes I think that having only one sample for batch 2 can be a problem to fit a model, but it is something different from the confounding effect which generated your error.
Hugo
