### ISSUE TITLE
possibility of using other inputs

### ISSUE THREAD

**Issue by baj12** [PF2-pasteur-fr/SARTools#27]
It would be nice to have other options of supplying the data. I.e. the IonTorrent technologies provide one file with all the counts for all experiments per chip. I now have to separate them into individual files, which boils down to a lot of code around formatting of data that is unnecessary, also the problem of the factors being a number could be avoided if I could use data frames as input (just like DESeq2)...

**Comment by hvaret** [comment]
Hi Bernd,
sorry for the delay. The importation of the data is a key step in SARTools for non-advanced users and the structure of the package makes the modifications difficult. I already thought to let the user supplying a matrix containing all the samples but it would be dangerous if the samples are not correctly linked to the target design object.
Best,
Hugo
