### ISSUE TITLE
"The factor of interest group has a level without replicates"

### ISSUE THREAD

**Issue by u9090** [PF2-pasteur-fr/SARTools#28]
Hi,

Is it possible to compare 2 conditions without having replicates?

My target.txt:
```
label    files    group
sample1_cond1    s1_c1_target.txt    CONDITION1
sample1_cond2    s1_c2_target.txt    CONDITION2
```

When running SARTools I get:
```
[1] "All the parameters are correct"
Error in loadTargetFile(targetFile = targetFile, varInt = varInt, condRef = condRef,  : 
  The factor of interest group has a level without replicates
Execution halted
```

What am I doing wrong?

Thanks !

**Comment by hvaret** [comment]
Hi,
from a statistical point of view it is very dangerous to compare 2 conditions without biological replicates (bad FDR control, low power), that's why SARTools returns an error. Moreover, I think both DESeq2 and edgeR would return an error too.
Best,
Hugo
