### ISSUE TITLE
Extract DESeq2 normalized count table after SARTools run

### ISSUE THREAD

**Issue by TokeB-A** [PF2-pasteur-fr/SARTools#30]
Hi Hugo,

I would like to extract the normalized count table after I succesfully have runned SARTools.

I might have found the solution, but could you please confirm this or guide me in the right direction.

The command I used to extract the DESeq2 normalized counttable after SARTool run:

foo <- counts(out.DESeq2$dds, normalized = TRUE)
write.csv(foo, file="norm_counts.csv")

Thank you very much in advance.

**Comment by hvaret** [comment]
Hi,
I confirm that your code is correct to export the normalized counts computed with DESeq2.
Hugo

**Comment by TokeB-A** [comment]
Thanks!
