### ISSUE TITLE
New normalization methods

### ISSUE THREAD

**Issue by bfoquet** [PF2-pasteur-fr/SARTools#32]
Hi,

I wondered whether it is possible to add the new normalization methods described [Li et al., 2017](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0176185#pone.0176185.s009) to SARTools? This paper describes two new normalization methods to be used in combination with edgeR, that might perform better for RNA-seq data skewed towards lowly expressed read counts with high variation.

Complete reference: Li, X., Brock, G. N., Rouchka, E. C., Cooper, N. G., Wu, D., O’Toole, T. E., ... & Rai, S. N. (2017). A comparison of per sample global scaling and per gene normalization methods for differential expression analysis of RNA-seq data. PloS one, 12(5), e0176185.

**Comment by hvaret** [comment]
Dear @bfoquet,
thanks for your suggestion and sorry for the delay! Unfortunately I think it will be difficult to add a new normalization method to SARTools with the current stucture of the code, and I would prefer to let only those available within edgeR or DESeq2.
Best regards,
Hugo
