### ISSUE TITLE
adding the parameter parallel for DESeq pipeline

### ISSUE THREAD

**Issue by Imoteph** [PF2-pasteur-fr/SARTools#37]
Just wondering the reason why this flag can not be set in SARTools. Or maybe I missed something.

**Comment by hvaret** [comment]
Hi,
Do you mean the parallel parameter of the DESeq() function in DESeq2? I understand that it could be nice to have access to more parameters but the goal of SARTools is to simplify the differential analysis using the most standard and important parameters. For advanced users I would recommend using either DESeq2 or edgeR directly.
Best regards,
Hugo

**Comment by Imoteph** [comment]
Hi Hugo

thx for your response. I was just wondering as it "would" only be adding the BiocParallel package and activating the parallel keyword in the script for the "normal simple cases". 

Nevertheless thank you for the package. Did you thought about packaging it also for galaxy?

**Comment by hvaret** [comment]
Yes there is a SARTools wrapper for Galaxy available at https://toolshed.g2.bx.psu.edu/repository?repository_id=cdf3b3a37a9fa65e

**Comment by Imoteph** [comment]
thx!
