### ISSUE TITLE
getopt error: redundant short names

### ISSUE THREAD

**Issue by shekeb** [PF2-pasteur-fr/SARTools#42]
in file `template_script_edgeR_CL.r`, short name `"-g"` is used twice: once on line 69, and again on line 84. 

`Rscript template_script_edgeR_CL.r --targetFile target.tsv --rawDir ../. --condRef "CT"`

fails with ...

```
Error in getopt(spec = spec, opt = args) : 
  redundant short names for flags (column 2 of spec matrix).
Calls: parse_args -> getopt
Execution halted
```

editing `"-g"` on line 84 to `"-g2"` resolves the conflict and error.

**Comment by hvaret** [comment]
Hi,
thanks for the bug report. I modified the shortcut and it is now "-f" in the development branch. I'll push to the master branch when there will me major changes.
Best,
Hugo
