### ISSUE TITLE
update the conda repo?

### ISSUE THREAD

**Issue by scottdaniel** [PF2-pasteur-fr/SARTools#48]
Hi,

Could you update the bioconda repository so that the latest changes can be gotten from there? In my environment its much easier to do `conda install -y -c bioconda r-sartools`

**Comment by hvaret** [comment]
Hi,
I'm updating the conda recipe, I will let you know when everything is OK.
Best,
Hugo

**Comment by hvaret** [comment]
Done!

**Comment by scottdaniel** [comment]
Thanks!
