### ISSUE TITLE
unable to install SARTools via conda with optparse

### ISSUE THREAD

**Issue by scottdaniel** [PF2-pasteur-fr/SARTools#50]
Hi, since I'm incorporating your scripts into a command-line pipeline, I need the r-optparse library as part of my environment. Both of these commands fail:
`conda install -c bioconda r-optparse r-sartools=1.6.3`
and
`conda install -c conda-forge r-optparse; conda install -c bioconda r-sartools=1.6.3`

They both give the error:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - r-sartools=1.6.3
```

Any ideas? p.s. I'm building this as part of a singularity container for future-compatibility so I attached my full [Build spec] in case you want to take a look at my full setup
[image.txt](https://github.com/PF2-pasteur-fr/SARTools/files/2063685/image.txt)

Also tried installing into a completely new environment:
`conda create -n sartools r-sartools=1.6.3`

**Comment by hvaret** [comment]
Hi,
sorry I do not see the problem. Installing optparse from conda-forge seems to be better than from bioconda as the version is more recent, but it should not give an error (it works on my computer).
An idea: update conda with `conda update -n base conda` and define the priority of the channels according to the current guidelines: `conda config --add channels defaults; conda config --add channels conda-forge; conda config --add channels bioconda;`
Let me know if does not work.
Best,
Hugo

**Comment by scottdaniel** [comment]
Your idea worked, thanks so much!
