### ISSUE TITLE
How could I obtain homoscedastic normalized counts from SARtools ?

### ISSUE THREAD

**Issue by Bury-Mone** [PF2-pasteur-fr/SARTools#58]
Hello,
I would like to export the homoscedastic normalized counts obtained from SARtools to perform other multidimensional analysis. Could you please indicate to me how I can obtain them ?
I thank you a lot for this information.
Kind regards
Stéphanie (from Roscoff)

**Comment by hvaret** [comment]
Hi Stéphanie,
after having run the DESeq2 template script you can get the variance-stabilized counts using:
`vsd <- getVarianceStabilizedData(out.DESeq2$dds)`
Best,
Hugo

**Comment by Bury-Mone** [comment]
Dear Hugo, 
I thank you very much for your help. 
Have a nice day, 
Stéphanie. 

----- Mail original -----

De: "Hugo Varet" <notifications@github.com> 
À: "PF2-pasteur-fr/SARTools" <SARTools@noreply.github.com> 
Cc: "Bury-Mone" <stephanie.bury-mone@u-psud.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 17 Décembre 2018 14:14:17 
Objet: Re: [PF2-pasteur-fr/SARTools] How could I obtain homoscedastic normalized counts from SARtools ? (#58) 



Hi Stéphanie, 
after having run the DESeq2 template script you can get the variance-stabilized counts using: 
vsd <- getVarianceStabilizedData(out.DESeq2$dds) 
Best, 
Hugo
