### ISSUE TITLE
2 time points and no other condition 

### ISSUE THREAD

**Issue by vmkalbskopf** [PF2-pasteur-fr/SARTools#59]
I have 9 biological replicates where RNA was sequenced at 2 times points (Day 8 and 20). There are no other conditions.
My samples look like this:

D8Bird1
D8Bird2
...
D8Bird9
D20Bird1
....
Day20Bird9

I want to look at differential expression between the two time points. Do I simply treat each time point as a condition?

**Comment by vmkalbskopf** [comment]
For some reason, I didn't get notified about your response, but thank you!

I have a followup question.
How does the statistical model account for the fact that Bird1 in time point 1 is the same bird in time point 2 when testing significantly deferentially expressed genes.
I made a change to my target.txt file, and added a BioRep column, but I don't know if it makes a difference, or if it is interpreted as I hope it is.

 label   files   condition       BioRep
D20B11  D20_Bird11_0-1p.count   D20     B11
D20B12  D20_Bird12_4-8p.count   D20     B12
D20B13  D20_Bird13_4p.count     D20     B13
D20B14  D20_Bird14_0-3p.count   D20     B14
D20B6   D20_Bird6_56-4p.count   D20     B6
D20B7   D20_Bird7_0-24p.count   D20     B7
D20B8   D20_Bird8_4p.count      D20     B8
D8B11   D8_Bird11_33-4p.count   D8      B11
D8B12   D8_Bird12_56p.count     D8      B12
D8B13   D8_Bird13_7p.count      D8      B13
D8B14   D8_Bird14_57-1p.count   D8      B14
D8B6    D8_Bird6_61-7p.count    D8      B6
D8B7    D8_Bird7_14-4p.count    D8      B7
D8B8    D8_Bird8_42-3p.count    D8      B8

**Comment by hvaret** [comment]
Hi,
in your experiment the biological factor of interest is the day (i.e. the condition column of your target file), and you can specify that the BioRep column must be treated as a blocking factor (batch parameter of the SARTools script). In other words, it is similar to performing a paired test.
Best regards,
Hugo

**Comment by vmkalbskopf** [comment]
I feel like I'm missing something. In a paired test, the (normalised) means of all the birds in each condition are compared between condition, right? What I am hunting for is if the individual bird expression levels are compared between conditions, since the same bird is present in each condition. How is that accounted for?

**Comment by hvaret** [comment]
> In a paired test, the (normalised) means of all the birds in each condition are compared between condition, right?

In a paired test, we first compute the difference D=D8-D20 for each bird and then test for the null hypothesis D=0. If the test is not paired, we test for the null hypothesis D8=D20 without computing the difference as there is no link between the first replicate of D8 and the first replicate of D20.

Hope this helps.

**Comment by vmkalbskopf** [comment]
It helps a little bit.
With out the BioRep grouping, how does the model know which birds to compare? Or does it compare all birds to all birds between time points?

**Comment by hvaret** [comment]
It is impossible to know which birds to compare without the BioRep column, that's why you need it and must pass the column name to the batch argument of the SARTools script.

**Comment by vmkalbskopf** [comment]
Thank you!
I'm getting quite different results now!
