### ISSUE TITLE
figure format and size

### ISSUE THREAD

**Issue by xandinho2468** [PF2-pasteur-fr/SARTools#6]
Figure format should be costumizable and size also

The images are too small at 400x400

also format of the image output could be pdf or other vector based format.

**Comment by hvaret** [comment]
Thanks for your suggestions. In the development version the figure size is adapted according to the number of samples, I am still working on it before merging with the master branch. I agree that vector based formats are nicer, I had already tried with PDF figures but the integration into the HTML report was more difficult. Please feel free if you have any idea!

**Comment by CTLife** [comment]
You can generate PDF(EPS or SVG)  and PNG figures, and  integrate PNG figures into the HTML report.    So   vector based formats are OK for papers,  and PNG figures are used for HTML report.

**Comment by hvaret** [comment]
Dear xandinho2468,
just to let you know that I have improved the figures (size and resolution) in the development version of SARTools. It will go to the master branch in a few days.
Best regards,
H
