### ISSUE TITLE
SARTools DESeq2 and EdgeR output tables have non consistent columns

### ISSUE THREAD

**Issue by ppericard** [PF2-pasteur-fr/SARTools#60]
Hi,
I've been running RNAseq DE analysis comparing the results from DESeq2 and EdgeR. One of my last step consist in extracting from the output table "*.complete.txt" the DE genes using filters on the log2(FC) and the ajusted pvalue.
I just realized by chance that there is a pb of consistency in the column numbers of this file between DESeq2 and EdgeR SARTools outputs.

I based my scripts on the EdgeR columns where the log2(FC) is in column 18, and the adjusted pvalue is column 20. However, in the DESeq2 file the first 18 column are consistent with the EdgeR file but the "stat" column is inserted between the log2(FC) and pvalue column. 
What that means is that if you go over it a bit fast like I did, you end-up filtering on the pvalue column instead of the adjusted pvalue.

Maybe so that the 2 files are more consistent it would be a good idea to have the same first 20 columns the same in both file format. And so that inattentive users like me don't do this kind of mistake.

Thanks.

**Comment by hvaret** [comment]
Hi,
thanks for your message. I understand your issue but I think the DESeq2 and edgeR tables exported were similar by chance (before I introduced the "stat" column). I would advise you to extract the log2FC and adjusted P-values with R using the exact column names and not their indexes.
Best regards,
Hugo

**Comment by ppericard** [comment]
Hi,
Thank you for your quick answer. In my case I'm post-processing the data outside of R, in bash, which is why it was a pb because I didn't double check the 2 files. I understand that it is not a bug, I was just pointing out a potential improvement in terms of file format consistency.
However I definitely don't have the perspective you have on use cases and what users are doing with those files, and I also know how script-breaking these file format changes can be, so I would totally understand if you don't change anything ;-) 
Cheers,
Pierre
