### ISSUE TITLE
More flexible input formats

### ISSUE THREAD

**Issue by KField-Bucknell** [PF2-pasteur-fr/SARTools#61]
I have forked the repo to add a feature that I have long desired in SARTools. My plan is to provide flexibility in input formats without changing the default behavior for beginner users. 

I have added two new parameters for loadCountData: idColumn and countColumn. The defaults will be 1 and 2 (assuming data like htseq-count). If users want to provide other input, like featurecounts or the output from Kallisto or Salmon, they they will have to tell SARTools where to find the count column.

I have also added a step in loadCountData to round off the counts to integers (instead of just stopping with an error). This is very helpful for anyone providing RSEM, Kallisto, or Salmon counts files.

I hope that you find this helpful and will consider incorporating it into the next version.

**Comment by KField-Bucknell** [comment]
I have made changes to the following files on my branch (https://github.com/KField-Bucknell/SARTools):
```
R/loadCountData.R
template_script_DESeq2.r
template_script_DESeq2_CL.r
template_script_edgeR.r
template_script_edgeR_CL.r
```
I have tested the R scripts, but not the command-line versions. I have tested with RSEM and Salmon input, but not kallisto, featureCounts, or htseq-count.

I have not updated the vignette. 

Please let me know if you think this feature would be helpful and I can provide further testing and documentation.

**Comment by hvaret** [comment]
Hello,

thank you for your interest in SARTools and all the changes you have made, and sorry for the long delay.

I do not know which version you started from, but the loadCountData() function automatically recognizes the input format in the current version of SARTools (it makes some tests and then decides which columns to use).

Then, I think it is better (and recommanded) to load RSEM/salmon/kallisto files using the tximport R package before any downstream analysis with DESeq2. I would thus prefer to keep SARTools dedicaded to the analysis of count files generated by standard aligners like STAR + featureCounts/HTSeq-count.

Feel free to let me know if you have any question.

Best regards,

Hugo
