### ISSUE TITLE
Manual limits on MA plot and Volcano plot

### ISSUE THREAD

**Issue by KField-Bucknell** [PF2-pasteur-fr/SARTools#62]
In my branch of SARTools I have also added an optional feature to both summarizeResults.DESeq2.r and summarizeResults.edgeR.r. This feature allows the manual setting of the ylim for the MA plot and the Volcano plot using the parameters `FClimit` and `adjPlimit`. If these parameters are not used, the behavior is identical to the current functions.

This feature is designed to solve two problems. (1) When you want to compare MA plots between similar analyses. (2) The volcano plot looks very ugly when the p-values are high for a given analysis.

**Comment by hvaret** [comment]
Hi,
thanks for the suggestion. I've just added the new parameters in the MAplot(), volcanoPlot(), summarizeResults*() functions and pushed the changes to SARTools 1.6.7 in the master branch. The new parameters are actually named log2FClim (numeric vector of length 2 for the lower and upper bounds) and padjlim (numeric value between 0 and 1 that will be log10-transformed).
Best,
Hugo
