### ISSUE TITLE
install SARTools in RSTUDIO

### ISSUE THREAD

**Issue by SMORTAZA** [PF2-pasteur-fr/SARTools#63]
Hi,
I would like to install SARTools but I get the error below ;
\> install_github("PF2-pasteur-fr/SARTools", build_vignettes=TRUE)
Downloading GitHub repo PF2-pasteur-fr/SARTools@master
sh: 1: /bin/gtar: not found

gzip: stdout: Broken pipe
sh: 1: /bin/gtar: not found

gzip: stdout: Broken pipe
Error in system(cmd, intern = TRUE) : error in running command
In addition: Warning message:
In utils::untar(tarfile, ...) :
  ‘/bin/gzip -dc '/tmp/RtmpaKnPjj/file5af435bec50b.tar.gz' | /bin/gtar -xf '-' -C '/tmp/RtmpaKnPjj/remotes5af44c43b3a6'’ returned error code 127
\> 

Would you have you a solution ?

Thanks in advance.
SM

**Comment by hvaret** [comment]
Hi,
It seems that the "gtar" command is not available but I never had this error, what OS are you using?
Best,
Hugo

**Comment by SMORTAZA** [comment]
Hi,
I am using ubuntu 16.04 LTS, 64 bit.
SM

**Comment by hvaret** [comment]
OK, I think the best is to try to install `gtar`: something like `sudo apt-get install gtar` should work.
Best,
HV
