### ISSUE TITLE
Adjust font size

### ISSUE THREAD

**Issue by vmkalbskopf** [PF2-pasteur-fr/SARTools#66]
Hi there!
Is it possible to adjust the font size in the plots? Specifically I would like to change the font size in the Pairewise scatter plot. As you can see, the labels are too large for the boxes. How do I access the source code for the image?
![pairwisefontproblem](https://user-images.githubusercontent.com/22935643/58165468-28001000-7c88-11e9-9909-4b1f6ad8019f.png)

**Comment by hvaret** [comment]
Hi,
it is a bit difficult to automate the size of the labels, but you can modify and load in your environment the pairwiseScatterPlots() function available here: https://github.com/PF2-pasteur-fr/SARTools/blob/master/R/pairwiseScatterPlots.R 
You can use `cex=sqrt(ncol)` and `cex.labels=sqrt(ncol)` lines 20 and 25 respectively, or any other constant value which fits well with your labels.
Hope this helps.
Hugo

**Comment by hvaret** [comment]
Hi,
just to let you know that I updated SARTools to integrate these changes.
Best regards,
Hugo
