### ISSUE TITLE
Option to save figures as eps files that can be edited in programs like Inkscape and Illustrator

### ISSUE THREAD

**Issue by vmkalbskopf** [PF2-pasteur-fr/SARTools#72]
ggplot has the the ability to save plots as eps files, which are scalar vector graphics, so you have high (infinite) resolution images (not bitmaps). 

In addition, objects like text in the image can be edited in drawing programs like Inkscape and Adobe Illustrator.

Here's a simple example of the ggsave function:
```
plot <- ggplot(df, aes(y=y1, x=x1)) +geom_point()
ggsave('test.eps', plot)
```

Those are the pros, but there are cons, for example Microsoft Office does not support eps files. But perhaps perhaps both the old png and new eps figures can be generated?

**Comment by hvaret** [comment]
Dear @vmkalbskopf,
thanks for your suggestion, I fully understand the advantage of the .eps/.pdf formats, but exporting figures in both .png and .eps would make the code more complex and I would prefer keeping it as simple as possible.
Feel free to let me know if you wish to export a specific figure in .eps, I can help you to write the corresponding R code.
Best regards,
Hugo

**Comment by vmkalbskopf** [comment]
Hmmm... I took a look at some of the figure functions, and they're already quite complex, so I understand why you'd want to keep it as it is.

Thanks for your offer :-) 
I would like to customise a few figures,  especially the PCA, cluster dendogram, percentage of null counts per sample. 
I installed sartools via conda. I don't really understand how r packages are compiled, because I can't find the R scripts in my anaconda directory. So I tried editing the functions using the trace command in R:
`trace('pairwiseScatterPlots()', edit=TRUE)`
But that feels fragile. If I update the package I will lose any changes. What do you recommend?

**Comment by hvaret** [comment]
I think the best option is to insert custom R code in the template R script to export the figures in .eps. Immediately after the call to `descriptionPlots()` you can insert:
```
postscript("figures/barplotNull.eps", width=10, height=7)
barplotNull(counts=counts, group=target[,varInt], col=colors, outfile=FALSE)
dev.off()
```
and then after the call to `exploreCounts()` (if you use DESeq2):
```
if (typeTrans == "VST"){
  counts.trans <- assay(varianceStabilizingTransformation(out.DESeq2$dds))
} else{
  counts.trans <- assay(rlogTransformation(out.DESeq2$dds))
}
postscript("figures/PCA.eps", width=10, height=7)
PCAPlot(counts.trans=counts.trans, group=target[,varInt], col=colors, outfile=FALSE)
dev.off()
postscript("figures/cluster.eps", width=10, height=7)
clusterPlot(counts.trans=counts.trans, group=target[,varInt], outfile=FALSE)
dev.off()
```
Hope this helps!

**Comment by vmkalbskopf** [comment]
YES! This is excellent!
I needed to change the width and height of the PCA since it's 2 plots in one image. And I increased the pointsize.
Ended up with this:
`postscript("figures/PCA.eps", width=13, height=5, pointsize=20)`

I have one or two other customisations I'd like to make, but I'll put those in another post.

Thank you!
