### ISSUE TITLE
Option to set ggplot themes

### ISSUE THREAD

**Issue by vmkalbskopf** [PF2-pasteur-fr/SARTools#73]
After a recent update, all of the plots use the default ggplot theme, with the grey background. I would like to use alternative themes, like the light theme. Is this possible?

**Comment by hvaret** [comment]
Hi,
I just modified the development version of SARTools to be able to use the light theme. You'll have to add `ggplot_theme=theme_light()` in three functions (not in the parameters at the top of the scripts):
 - `descriptionPlots()`
 - `exploreCounts()`
 - `summarizeResults.*()`

This new feature will appear in the master branch when I have enough changes to push. If you want to test it now you can install the development version using:
`install_github("PF2-pasteur-fr/SARTools", build_opts="--no-resave-data", ref="development")`
Best,
Hugo

**Comment by vmkalbskopf** [comment]
Thank you!!
