### ISSUE TITLE
edgeR error “arguments imply differing number of rows: 2, 15, 1” after explorecounts

### ISSUE THREAD

**Issue by ACuriousScientist** [PF2-pasteur-fr/SARTools#75]
Hello,
I’m fairly new with R and RNA-seq analysis in general. I apologize in advance if this is an inappropriate place to post my issue. 

I am currently running a differential expression analysis using both DESeq2 and edgeR, I really like the reports generated by SARTools. I have managed to successfully run DESeq2, however, I encountered an error when running edgeR on the same input files. It happens after the explorecounts function and gives the message “arguments imply differing number of rows: 2, 15, 1”. 

To give a bit of context about my input files, I’m doing differential expression analysis across 5 groups, each with a total of three replicates. The input data consists of fifteen samples of raw counts as a tabular file. 
I appreciate any guidance on this matter. Thanks.

**Comment by hvaret** [comment]
Dear @ACuriousScientist,
thanks for your interest in SARTools. I reproduced the error with one of my dataset and fixed the issue in the development branch. You can install it using:
`install_github("PF2-pasteur-fr/SARTools", build_opts="--no-resave-data", ref="development")`
Best regards,
Hugo

**Comment by ACuriousScientist** [comment]
Hi Hugo,
The edgeR analysis worked after reinstalling the package using the command you mentioned. Thanks!
