### ISSUE TITLE
Error in loadTargetFile

### ISSUE THREAD

**Issue by canulef3** [PF2-pasteur-fr/SARTools#78]
Hello,
I have an error when I'm in this step in the template of DESeq2:
`target <- loadTargetFile(targetFile=targetFile, varInt=varInt, condRef=condRef, batch=batch)`
`Error in loadTargetFile(targetFile = targetFile, varInt = varInt, condRef = condRef,  : 
  The factor of interest NPC is not in the target file`

And my target file (separated by tab) is:

labels	file	group
iPSC1	ae_HIPSC_ipscbam1.txt	iPSC
iPSC2	ae_HIPSC_ipscbam2.txt	iPSC
NPC1	ae_HIPSC_npcbam1.txt	NPC
NPC2	ae_HIPSC_npcbam2.txt	NPC

I don't know what's wrong, can you help me please?

**Comment by hvaret** [comment]
Dear @canulef3,
I think there is an extra space before or after "NPC" in your target file (or maybe another invisible character). Could you please check that? Otherwise you can send me the file by e-mail so that I can read it on my own computer.
Best regards,
Hugo

**Comment by canulef3** [comment]
![Captura de Pantalla 2020-08-11 a la(s) 11 02 28](https://user-images.githubusercontent.com/42225398/89913861-35255980-dbc2-11ea-988c-d245a9cfeb0a.png)

this is how it's looks when check the invisible characters.

**Comment by canulef3** [comment]
[target.txt](https://github.com/PF2-pasteur-fr/SARTools/files/5057748/target.txt)

and this is the target file that I'm working with

**Comment by hvaret** [comment]
OK the problem does not come from the target file but from the parameters you have defined. You have to set up:
`varInt <- "group"` and `condRef <- "NPC"`, I think you have mixed these two parameters in your R script.

**Comment by canulef3** [comment]
Dear @hvaret 
Thank you! It worked 🎉
