### ISSUE TITLE
Error in loadCountData - release 1.7.3

### ISSUE THREAD

**Issue by loraine-gueguen** [PF2-pasteur-fr/SARTools#79]
Hi Hugo,

A user has the following error (within galaxy). 
It seems that there is a problem in the `if` condition here : https://github.com/PF2-pasteur-fr/SARTools/blob/master/R/loadCountData.R#L64
Do you know how to solve that ?
Cheers,
Loraine

```
    ----------------------------------------------
    Welcome to SARTools version 1.7.3.
    R template scripts are available on GitHub.
    ----------------------------------------------
There were 13 warnings (use warnings() to see them)
[1] "All the parameters are correct"
Target file:
          label              files group
Mock_M2 Mock_M2 dataset_928292.dat  Mock
Mock_M3 Mock_M3 dataset_928293.dat  Mock
Mock_M4 Mock_M4 dataset_928294.dat  Mock
CaMV_C1 CaMV_C1 dataset_928295.dat  CaMV
CaMV_C2 CaMV_C2 dataset_928296.dat  CaMV
CaMV_C3 CaMV_C3 dataset_928297.dat  CaMV
TuYV_T1 TuYV_T1 dataset_928298.dat  TuYV
TuYV_T2 TuYV_T2 dataset_928299.dat  TuYV
TuYV_T3 TuYV_T3 dataset_928300.dat  TuYV
Loading files:
dataset_928292.dat: 27656 rows and 5660 null count(s)
dataset_928293.dat: 27656 rows and 5715 null count(s)
dataset_928294.dat: 27656 rows and 6050 null count(s)
dataset_928295.dat: 27656 rows and 5440 null count(s)
dataset_928296.dat: 27656 rows and 5581 null count(s)
dataset_928297.dat: 27656 rows and 5539 null count(s)
dataset_928298.dat: 27656 rows and 5818 null count(s)
dataset_928299.dat: 27656 rows and 5614 null count(s)
dataset_928300.dat: 27656 rows and 5810 null count(s)
Error in counts%%1 : non-numeric argument to binary operator
Calls: loadCountData
Execution halted
```

**Comment by loraine-gueguen** [comment]
I suspect that the error is due to the presence of headers on the count files.

**Comment by hvaret** [comment]
Hi Loraine,
thanks for the feedback. Yes the bug probably comes from the headers, the loadCountData() function accepts either HTSeq-count files (2 tab-separated columns without headers) or featureCounts files (7 tab-separated columns with headers). Do you know how the user obtained the count files?
Best,
Hugo

**Comment by a-velt** [comment]
Hi Loraine and Hugo,

For featureCounts, on Galaxy, the "output format" option was set to "GeneId \t read-count". I will change to "featureCounts default", maybe it will work. I will keep you informed.

Best
Amandine

**Comment by loraine-gueguen** [comment]
Unfortunately, the sartools preprocess tool is not designed for featureCounts output with the "1.4.0+ default" format (7 tab-separated columns with headers). It generates an error.

So, at this point, with Galaxy, the solution is to use the default format in Galaxy of featureCount (2 columns), remove the header to get a htseq-count alike file (for example with with the "Remove beginning of a file" tool) and then run the preprocess sartools tool.

**Comment by hvaret** [comment]
Hi Loraine,
Sorry for the late answer. I think the best is to change the preprocess tool in order to let SARTools accept only default output types (two columns without header for HTSeq and 7 columns with headers for featureCounts).
Best,
Hugo

**Comment by marwa38** [comment]
I am getting the same error 
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/74d65a5f-62f5-487c-a355-a9456fa10581)
here are my input files 
what do you think, please?
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/85b2441b-e578-4901-a53f-9e1eca25130a)
for STIMM_REP1
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/8c192b56-c762-4748-b190-493966551232)
here is the target file 
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/eb78b9b2-2c9e-415a-a362-b986d95414d3)

**Comment by marwa38** [comment]
[info_session.txt](https://github.com/PF2-pasteur-fr/SARTools/files/11635206/info_session.txt)
