### ISSUE TITLE
add limma and voom into SARTools

### ISSUE THREAD

**Issue by CTLife** [PF2-pasteur-fr/SARTools#8]
Hi hvaret, 
                                       
  SARTools is very useful.
   But how to add limma and voom into SARTools ?
               
template_script_DESeq2.r  and template_script_edgeR.r  are available, 
if template_script_limmaVoom.r is also available, SARTools will be perfect.

Thank you.

**Comment by hvaret** [comment]
Hi CTLife,
sorry for the very long delay. We do not plan to make a limma/voom script for the moment because we are not familiar enough with this method. However I will let you know if we decide to make one.
Best,
H
