### ISSUE TITLE
descriptionPlots error due to tabSERE/SERE code

### ISSUE THREAD

**Issue by SedaArat** [PF2-pasteur-fr/SARTools#82]
Hi there, 

I experience an issue "Error in `[.data.frame`(fullObserved, fullKeep) : undefined columns selected" when running desriptionPlots. I traced it down to tabSERE and then SERE code at the perason chisq test: 

oeFull <- (fullObserved[fullKeep] - fullExpected[fullKeep])^2/ fullExpected[fullKeep] # pearson chisq test

I have fullKeep like 24 thousand entries and fullObserved has only 12 thousand rows and 2 columns. fullObserved[fullKeep] looks for 24 thousand columns that fullObserved does not have. Can you please comment on that? Do you think have a different issue, not the SERE problem?

Thanks,
Seda

**Comment by hvaret** [comment]
Hi,
thanks for your message. Unfortunately I've never met this error, my feeling is that your data might have a particular structure. Could you please send me the result of `save.image(file="SARTools_image.RData")` by e-mail so that I can try to reproduce the error on my own computer?
Best,
Hugo

**Comment by jtourig** [comment]
I had a similar issue; casting my data frame of counts `as.matrix()` first seemed to solve it.
