### ISSUE TITLE
SarTools Cloud Version

### ISSUE THREAD

**Issue by MakeTheBrainHappy** [PF2-pasteur-fr/SARTools#86]
Dear SarTools Developers, 

In my previous correspondence I mentioned having implemented SarTools on Google Colaboratory, a free version of Juypter notebook which runs in the Cloud ([more information](https://colab.research.google.com/notebooks/intro.ipynb?utm_source=scs-index)). Would you be interested in a contribution to the "How to use SARTools?" section containing a link to this cloud-based version which syncs to users google drive accounts? 

Thank you for your consideration.

Sincerely,
MTBH

**Comment by hvaret** [comment]
Hi,
Sure it could be useful to insert a link to the version of SARTools you've implemented in Google Colaboratory. Could you please add a small sentence to the README file and then make a merge request onto the dev branch?
Best regards,
Hugo

**Comment by MakeTheBrainHappy** [comment]
Hi Hugo,

My apologies for the delay. I decided to make a couple of edits to the notebook to make it more user-friendly. Hopefully I submitted everything correctly! Thank you very much. 

Sincerely,
MTBH

**Comment by hvaret** [comment]
Hi,
everything is fine, I have been able to merge the two branches. Thanks again for your suggestion!
Best,
Hugo
