### ISSUE TITLE
input files format

### ISSUE THREAD

**Issue by cdecraene** [PF2-pasteur-fr/SARTools#87]
dear SARTools team,

as describe in your paper, as input files, count data files are sample-specific and are
composed of two columns (a unique feature identifier and a raw feature count) with no header. using this format I have :

 " Error in loadCountData(target = target, rawDir = rawDir, featuresToRemove = featuresToRemove) :   Can't determine if count files come from HTSeq-count or featureCounts "

thanks for your help 

best 

Charles

**Comment by hvaret** [comment]
Dear @cdecraene,
thanks for you message. My first feeling is that your input files are not exactly as expected, could you please double check the header and the column separator? Otherwise you can send me one of them and I'll try to find the issue.
Best,
Hugo

**Comment by cdecraene** [comment]
De: "Hugo Varet" ***@***.***> 
À: "PF2-pasteur-fr/SARTools" ***@***.***> 
Cc: "DECRAENE Charles, LNCA" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Lundi 26 Juillet 2021 08:04:00 
Objet: Re: [PF2-pasteur-fr/SARTools] input files format (#87) 





Dear [ https://github.com/cdecraene | @cdecraene ] , 
thanks for you message. My first feeling is that your input files are not exactly as expected, could you please double check the header and the column separator? Otherwise you can send me one of them and I'll try to find the issue. 
Best, 
Hugo

**Comment by cdecraene** [comment]
thank you for your quick response ! 

could you confirm the file format ? 

no header ? 
tab as column separator ? 

best 
C 

De: "Hugo Varet" ***@***.***> 
À: "PF2-pasteur-fr/SARTools" ***@***.***> 
Cc: "DECRAENE Charles, LNCA" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Lundi 26 Juillet 2021 08:04:00 
Objet: Re: [PF2-pasteur-fr/SARTools] input files format (#87) 





Dear [ https://github.com/cdecraene | @cdecraene ] , 
thanks for you message. My first feeling is that your input files are not exactly as expected, could you please double check the header and the column separator? Otherwise you can send me one of them and I'll try to find the issue. 
Best, 
Hugo

**Comment by hvaret** [comment]
I can't see your file, did you copy-paste its content or attach it?

**Comment by cdecraene** [comment]
here the data 

C 


De: "Hugo Varet" ***@***.***> 
À: "PF2-pasteur-fr/SARTools" ***@***.***> 
Cc: "DECRAENE Charles, LNCA" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Lundi 26 Juillet 2021 10:05:26 
Objet: Re: [PF2-pasteur-fr/SARTools] input files format (#87) 





I can't see your file, did you copy-paste its content or attach it?
