### ISSUE TITLE
p-value change with multiple condition

### ISSUE THREAD

**Issue by Flo5701** [PF2-pasteur-fr/SARTools#89]
Hello,

First of all, thank you for your very practical tool.
I want to do an analysis with Deseq2 with 12 samples distributed in 4 groups.
For the example, group A containing 3 samples is the control, I want to look at the inducibility of genes between group A Vs B, A Vs C and A Vs D.
So I used your script by putting group A as control, and everything works correctly. 
I get a table with the desired comparisons. 
But later to save time I did a new analysis (with the same parameters, same version of the script and R) only between group A and B.
I get the table A Vs B. 
The problem is that the first table A vs B obtained when I put the 4 groups is not the same as the table A Vs B when I put only the 2 groups A and B.
The Fold, Log2fold change is very small but the p-value and adjusted p-value change for some genes enormously. 
I wonder why adding conditions C and D interferes with the calculation of the p-value between A and B

I use the following parameters

targetFile <- "target2.txt"                           # path to the design/target file
rawDir <- "data"                                      # path to the directory containing raw counts files
featuresToRemove <- c("alignment_not_unique",        # names of the features to be removed
                      "ambiguous", "no_feature",     # (specific HTSeq-count information and rRNA for example)
                      "not_aligned", "too_low_aQual")# NULL if no feature to remove

varInt <- "group"                                    # factor of interest
condRef <- "w"                                      # reference biological condition
batch <- NULL                                        # blocking factor: NULL (default) or "batch" for example

fitType <- "parametric"                              # mean-variance relationship: "parametric" (default), "local" or "mean"
cooksCutoff <- TRUE                                 # TRUE/FALSE to perform the outliers detection (default is TRUE)
independentFiltering <- TRUE                      # TRUE/FALSE to perform independent filtering (default is TRUE)
alpha <- 0.05                                        # threshold of statistical significance
pAdjustMethod <- "BH"                                # p-value adjustment method: "BH" (default) or "BY"

typeTrans <- "VST"                                   # transformation for PCA/clustering: "VST" or "rlog"
locfunc <- "median"                                  # "median" (default) or "shorth" to estimate the size factors

colors <- c("dodgerblue","firebrick1",               # vector of colors of each biological condition on the plots
            "MediumVioletRed","SpringGreen")

forceCairoGraph <- FALSE

Thank you

Florent

**Comment by hvaret** [comment]
Hi,
thanks for your question. Actually it is normal to get different results for the comparison A vs B depending on whether there are other biological conditions C and D. The estimations of the size factors and dispersions are not the same, as well as the log2FC, and then the final results (e.g. p-values) for A vs B differ.
Best,
Hugo
