### ISSUE TITLE
LFC shrinkage

### ISSUE THREAD

**Issue by lmanchon** [PF2-pasteur-fr/SARTools#90]
--Hi,

why you don't use the new function lfcShrink() released in DESeq2 ?
sequencing datasets show better performance using this function such as: res <- lfcShrink(dds, coef=2, type="apeglm")

thank you --

**Comment by hvaret** [comment]
Hi,
thanks for your message. I agree that this new feature is interesting, and I will try to add it to SARTools when I have time.
Best,
Hugo

**Comment by hvaret** [comment]
log2FC from DESeq2 are now computed with apeglm.
