### ISSUE TITLE
reporting a ggplot warning 

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#95]
Just reporting this warning 
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/aa53f7a2-e1fa-4d92-b4af-0648f8e5131b)
I got after running
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/1234fc18-4868-4041-8d36-3cbfe9397c86)

**Comment by hvaret** [comment]
Hi,
thanks for the report. I'll try to modify the code to avoid this warning.
Best,
Hugo

**Comment by hvaret** [comment]
Fixed in the development version 1.8.2.

**Comment by marwa38** [comment]
thanks so much
