### ISSUE TITLE
warning: no scatter plot because of high nunber of samples?

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#97]
I don't know why I am getting this warning for the scatter plot?
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/d9d997fa-1b91-44f8-914e-8e8bb50f2842)
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/e7b02f0d-65df-43d6-b37b-9cc9dad14610)

![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/b69c7af2-bd6f-4d59-b1aa-43da754ff855)

Thanks 
Marwa

**Comment by hvaret** [comment]
Hi,
it is difficult to display a pairwise scatter plot with a lot of samples, so I defined a limit to avoid producing the figure when there is more than 12 samples.
Best regards,
Hugo
