### ISSUE TITLE
how to import rsem to use in SARTools?

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#98]
Thanks for the great package. 
Could you please help with importing rsem? I am getting the same integer error as reported in the below issue
tximport is asking to add sample data which I beleive is not possible for SARTools as there us a separate target file. 
Thanks in advance with your help. 

              Hi,
I do not remember exactly what tximport does, I only remember that there are several options to import the data (e.g. countsFromAbundance parameter in tximport() function). You can try to import RSEM files and then pass the matrix to SARTools modifying the R script, but make sure that the samples/columns are correctly ordered and named according to the target design file.
Best,
Hugo

_Originally posted by @hvaret in https://github.com/PF2-pasteur-fr/SARTools/issues/33#issuecomment-308968234_

**Comment by hvaret** [comment]
Hi,
Actually SARTools can't import RSEM results. I recommend you to refer to the tximport vignette to import the expression data and then use DESeq2 to perform the differential analysis.
Best,
Hugo

**Comment by marwa38** [comment]
is it not possible to just round() the rsem table and use it in SARTools?

**Comment by hvaret** [comment]
Hi,
it is possible from a technical point of view but not the recommended pipeline. It is preferable to use tximport as a link between RSEM and DESeq2.
Hugo
