### ISSUE TITLE
Scale for Y already present, adding another scale for y, which will replace the existing scale?

### ISSUE THREAD

**Issue by marwa38** [PF2-pasteur-fr/SARTools#99]
Hi,
After clearing the Rstudio environment why I might get this notification after running the following code?
Is it ok? thanks in advance 
![image](https://github.com/PF2-pasteur-fr/SARTools/assets/68851733/95933e6e-1bd6-43c7-b0c7-55da53f897b9)

**Comment by hvaret** [comment]
Hi,
yes it is expected because the y scale of the dendrogram is overwritten with ggplot2, you can ignore this message.
Hugo
